### ISSUE TITLE
Unrecognized function or variable 'cat_get_defaults'.

### ISSUE THREAD

**Issue by RJMullins** [ChristianGaser/tfce#1]
This used to work - I'm on macOS 12.6.3, matlab R2022a, SPM12 7771. I'm using TFCE as an SPM12 toolbox in the toolbox subfolder.

Would installing CAT12 get around this for now?

SPM12: cat_spm_results_ui                          22:24:43 - 27/03/2023
========================================================================
	SPM computation                 :                        ...done
Unrecognized function or variable 'cat_get_defaults'.

Error in cat_spm_results_ui (line 1116)
        [csv_files, n_csv] = cat_vol_findfiles(cat_get_defaults('extopts.pth_templates'), '*.csv');

Error in cat_spm_results_ui (line 494)
        hAtlasUI = cat_spm_results_ui('SetupAtlasMenu',Finter);
 
Error while evaluating DestroyedObject Callback.

**Comment by lrq3000** [comment]
I have the latest CAT12 toolbox in `spm12/toolbox/cat12` and indeed I did not get this error, the `Estimate TFCE` job completed fine.

**Comment by ChristianGaser** [comment]
Added checks for additional cat-tools that should be ignored if CAT12 is not installed.
